twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

    # permet d'ajouter les classes bootstrap 'form-group', 'form-control', rtc...
    form_themes:
        - bootstrap_4_layout.html.twig

    paths:
        '%kernel.project_dir%/vendor/knplabs/knp-paginator-bundle/templates': KnpPaginator
