-- --------------------------------------------------------
-- Hôte :                        127.0.0.1
-- Version du serveur:           10.4.11-MariaDB - mariadb.org binary distribution
-- SE du serveur:                Win64
-- HeidiSQL Version:             10.2.0.5599
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;


-- Listage de la structure de la base pour hobby
CREATE DATABASE IF NOT EXISTS `hobby` /*!40100 DEFAULT CHARACTER SET utf8mb4 */;
USE `hobby`;

-- Listage de la structure de la table hobby. article
CREATE TABLE IF NOT EXISTS `article` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `marque_id` int(11) DEFAULT NULL,
  `nom` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `ref1` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ref2` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `description` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tag1` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tag2` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tag3` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tag4` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tag5` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tag6` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `quantite` int(11) DEFAULT NULL,
  `filename` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `prix` double DEFAULT NULL,
  `quantite_min` int(11) DEFAULT NULL,
  `url` longtext COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `code_bar_number` int(11) DEFAULT NULL,
  `code_bar_text` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `type_code_bar` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  KEY `IDX_23A0E664827B9B2` (`marque_id`) USING BTREE,
  CONSTRAINT `FK_23A0E664827B9B2` FOREIGN KEY (`marque_id`) REFERENCES `marque` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=385 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPACT;

-- Listage des données de la table hobby.article : ~377 rows (environ)
DELETE FROM `article`;
/*!40000 ALTER TABLE `article` DISABLE KEYS */;
INSERT INTO `article` (`id`, `marque_id`, `nom`, `ref1`, `ref2`, `description`, `tag1`, `tag2`, `tag3`, `tag4`, `tag5`, `tag6`, `quantite`, `filename`, `updated_at`, `created_at`, `prix`, `quantite_min`, `url`, `code_bar_number`, `code_bar_text`, `type_code_bar`) VALUES
	(1, 15, 'article1', 'qsdsq', 'aaaa', 'sfsfsdfsdfsdf', NULL, NULL, '', NULL, NULL, NULL, 5, 'F-14A_Tomcat_tailhook.JPG', '2020-05-21 09:20:53', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(2, 15, 'article2', 'a', 'a', 'aas', NULL, NULL, NULL, NULL, NULL, NULL, 9, 'desgsdergserdgr.jpg', '2019-12-08 18:17:16', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(3, 15, 'article3', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 'Classic-Kit-letadlo-A19003-HAWKER-TYPHOON-1B-CAR-DOOR-1-24-_a72091046_10374.jpg', '2019-12-08 18:17:27', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(4, 15, 'article4', 'qsdsq', 'sqsdqsd', 'qsdqsds', NULL, NULL, NULL, NULL, NULL, NULL, 5, 'grumman-f14-tomcat_8.jpg', '2019-12-08 18:17:45', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(5, 15, 'article5', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 'grumman-f14-tomcat_20.jpg', '2019-12-08 18:17:54', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(6, 15, 'article65', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2, 'grumman-f14-tomcat_28.jpg', '2019-12-08 18:18:03', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(7, 15, 'article7', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 10, 'RetroF14SlowPass3oClock.jpg', '2020-05-21 09:15:49', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(8, 15, 'M3LEE early', NULL, 'MEDIUM TANK', NULL, 'maquette', 'plastique', '1/35', NULL, NULL, NULL, NULL, 'takom_m3_lee_early.png', '2020-05-21 09:20:44', '2019-12-12 18:47:03', NULL, NULL, NULL, NULL, NULL, NULL),
	(9, 15, 'M4 SHEREMAN early production', NULL, NULL, NULL, 'maquette', 'plastique', '1/35', NULL, NULL, NULL, NULL, 'undefined.jpg', NULL, '2019-12-12 19:31:42', NULL, NULL, NULL, NULL, NULL, NULL),
	(10, 15, 'AZV TANK (KRUPP)', NULL, NULL, NULL, 'maquette', 'plastique', '1/35', NULL, NULL, NULL, NULL, NULL, NULL, '2019-12-12 19:32:40', NULL, NULL, NULL, NULL, NULL, NULL),
	(11, 15, 'T34/85', NULL, NULL, NULL, 'maquette', 'plastique', '1/35', NULL, NULL, NULL, NULL, NULL, NULL, '2019-12-12 19:33:49', NULL, NULL, NULL, NULL, NULL, NULL),
	(12, 9, 'metallic blue', '49376036', 'X-13', NULL, 'peinture', 'acryl/alchool', '23ml', NULL, 'old', 'dilué', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(13, 9, 'blue', '49375947', 'X-4', NULL, 'peinture', 'acryl/alchool', '23ml', NULL, 'old', 'dilué', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(14, 9, 'german grey', '49376630', 'XF-63', NULL, 'peinture', 'acryl/alchool', '23ml', NULL, 'old', 'dilué', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(15, 9, 'ligth grey', NULL, 'XF-66', NULL, 'peinture', 'acryl/alchool', '23ml', NULL, 'old', 'dilué', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(16, 14, 'RLM light blue 65', '49372861', 'H67', 's', 'peinture', 'acryl/alchool', '10ml', NULL, 'old', 'dilué', 1, 'XF-84.png', '2020-05-22 14:01:34', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(17, 14, 'blue gray', '49372618', 'H42', NULL, 'peinture', 'acryl/alchool', '10ml', NULL, 'old', 'dilué', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(18, 9, 'black green', '49376470', 'XF-27', NULL, 'peinture', 'acryl/alchool', '23ml', NULL, 'old', 'dilué', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(19, 9, 'clear red', '49376173', 'X-27', NULL, 'peinture', 'acryl/alchool', '23ml', NULL, 'old', 'dilué', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(20, 9, 'smoke', '49376098', 'X-19', NULL, 'peinture', 'acryl/alchool', '23ml', NULL, 'old', 'dilué', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(21, 9, 'RML grey', NULL, 'XF-22', NULL, 'peinture', 'acryl/alchool', '23ml', NULL, 'old', 'dilué', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(22, 14, 'clear red', '49373097', 'H90', NULL, 'peinture', 'acryl/alchool', '10ml', NULL, 'old', 'dilué', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(23, 14, 'yellow', '49372236', 'H4', NULL, 'peinture', 'acryl/alchool', '10ml', NULL, 'old', 'dilué', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(24, 9, 'orange', '45032752', 'X-6', NULL, 'peinture', 'acryl/alchool', '10ml', NULL, NULL, 'dilué', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(25, 9, 'flat blue', '45035555', 'XF-8', NULL, 'peinture', 'acryl/alchool', '10ml', NULL, NULL, 'dilué', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(26, 9, 'flat white', '45035494', 'XF-2', NULL, 'peinture', 'acryl/alchool', '10ml', NULL, NULL, 'dilué', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(27, 9, 'flat black', '45035487', 'XF-1', NULL, 'peinture', 'acryl/alchool', '10ml', NULL, NULL, 'dilué', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(28, 9, 'flat yellow', '45035500', 'XF-3', NULL, 'peinture', 'acryl/alchool', '10ml', NULL, NULL, 'dilué', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(29, 9, 'titanium silver', '49376609', 'X-32', NULL, 'peinture', 'acryl/alchool', '10ml', NULL, NULL, 'dilué', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(30, 9, 'OLIVE DRAB', '45035883', 'XF-62', NULL, 'peinture', 'acryl/alchool', '10ml', NULL, NULL, 'dilué', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(31, 9, 'ligth grey', '45035920', 'XF-66', NULL, 'peinture', 'acryl/alchool', '10ml', NULL, NULL, 'dilué', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(32, 9, 'light brown (DAK 1942)', NULL, 'XF-93', NULL, 'peinture', 'acryl/alchool', '10ml', NULL, NULL, 'dilué', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(33, 9, 'yellow brown (DAK 1941)', NULL, 'XF-92', NULL, 'peinture', 'acryl/alchool', '10ml', NULL, NULL, 'dilué', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(34, 9, 'clear yellow', '45035432', 'X-24', NULL, 'peinture', 'acryl/alchool', '10ml', NULL, NULL, 'dilué', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(35, 9, 'clear orange', '49376166', 'X-26', NULL, 'peinture', 'acryl/alchool', '23ml', NULL, 'old', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(36, 9, 'chrome silver', '49376012', 'X-11', NULL, 'peinture', 'acryl/alchool', '23ml', NULL, 'old', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(37, 9, 'green', '49375954', 'X-5', NULL, 'peinture', 'acryl/alchool', '23ml', NULL, 'old', 'dilué', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(38, 9, 'lavis bleu citadel (botlle x-20a)', NULL, NULL, NULL, 'peinture', 'acryl/alchool', '10ml', NULL, 'old', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(39, 9, 'flat flesh', '45035623', 'XF-15', NULL, 'peinture', 'acryl/alchool', '10ml', NULL, 'old', 'dilué', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(40, 14, 'clear yellow', NULL, NULL, NULL, 'peinture', 'acryl/alchool', '10ml', NULL, 'old', 'dilué', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(41, 14, 'metal black', NULL, 'H28', NULL, 'peinture', 'acryl/alchool', '10ml', NULL, 'old', 'dilué', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(42, 14, 'blue (gloss)', '49372243', 'H5', NULL, 'peinture', 'acryl/alchool', '10ml', NULL, 'old 10%', 'dilué', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(43, 14, 'tan', '49372465', 'H27', NULL, 'peinture', 'acryl/alchool', '10ml', NULL, 'old', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(44, 14, 'RLM dark green 71 (sg)', '49372830', 'H64', NULL, 'peinture', 'acryl/alchool', '10ml', NULL, 'old', 'dilué', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(45, 14, 'fluorescent green (g)', '49373196', 'H100', NULL, 'peinture', 'acryl/alchool', '10ml', NULL, 'old', 'dilué', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(46, 14, 'oil', '49373615', 'H342', NULL, 'peinture', 'acryl/alchool', '10ml', NULL, 'old', 'dilué', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(47, 14, 'blue (gloss)', '49372243', 'H5', NULL, 'peinture', 'acryl/alchool', '10ml', NULL, 'old', 'dilué', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(48, 14, 'metallic red', '49373066', 'H87', NULL, 'peinture', 'acryl/alchool', '10ml', NULL, '20%', 'dilué', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(49, 14, 'shine rad (g)', '49372427', 'H23', NULL, 'peinture', 'acryl/alchool', '10ml', NULL, 'old', NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(50, 14, 'chair (flesh', '49372632', 'H44', NULL, 'peinture', 'acryl/alchool', '10ml', NULL, 'old', 'dilué', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(51, 14, 'brun cacao', '49372366', 'H17', NULL, 'peinture', 'acryl/alchool', '10ml', NULL, 'old', 'dilué', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(52, 14, 'gris ijn (g)', '49372809', 'H61', NULL, 'peinture', 'acryl/alchool', '10ml', NULL, 'old', 'dilué', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(53, 14, 'olive drab', NULL, 'H78', NULL, 'peinture', 'acryl/alchool', '10ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(54, 14, 'olive green', NULL, 'H405', NULL, 'peinture', 'acryl/alchool', '10ml', NULL, NULL, NULL, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(55, 14, 'black (f)', NULL, 'H12', NULL, 'peinture', 'acryl/alchool', '10ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(56, 14, 'gray FS 36231', NULL, 'H317', NULL, 'peinture', 'acryl/alchool', '10ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(57, 14, 'dark grey', NULL, 'H401', NULL, 'peinture', 'acryl/alchool', '10ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(58, 14, 'Dark Green BS381C/641', NULL, 'H330', NULL, 'peinture', 'acryl/alchool', '10ml', NULL, 'old', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(59, 14, 'ija green', NULL, 'H60', NULL, 'peinture', 'acryl/alchool', '10ml', NULL, 'old', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(60, 14, 'Gray FS 36375', NULL, 'H308', NULL, 'peinture', 'acryl/alchool', '10ml', NULL, 'old', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(61, 14, 'RLM02 Gray', NULL, 'H70', NULL, 'peinture', 'acryl/alchool', '10ml', NULL, 'old', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(62, 14, 'Gray FS 36270', NULL, 'H306', NULL, 'peinture', 'acryl/alchool', '10ml', NULL, 'old', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(63, 14, 'Gray FS 36118', NULL, 'H305', NULL, 'peinture', 'acryl/alchool', '10ml', NULL, 'old', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(64, 14, 'RLM70 Black Green', NULL, 'H65', NULL, 'peinture', 'acryl/alchool', '10ml', NULL, 'old', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(65, 14, 'RLM65 Light Blue', NULL, 'H67', NULL, 'peinture', 'acryl/alchool', '10ml', NULL, 'old', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(66, 9, 'light green', NULL, 'X-15', NULL, 'peinture', 'acryl/alchool', '10ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(67, 1, 'Rose permanent  S1 PA', '1914501', NULL, NULL, 'peinture', 'alkyd', NULL, NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(68, 1, 'jaune  -itron winsor   S1 PA  37ml', '1914722', NULL, NULL, 'peinture', 'alkyd', NULL, NULL, NULL, NULL, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(69, 1, 'bleu outremer françai   S1 PA', '1914263', NULL, NULL, 'peinture', 'alkyd', NULL, NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(70, 1, 'Cerulean blue', '1914137', NULL, NULL, 'peinture', 'alkyd', NULL, NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(71, 1, 'Blan de titane', '1914644', NULL, NULL, 'peinture', 'alkyd', NULL, NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(72, 1, 'Terre de sienne brulé', '1914074', NULL, NULL, 'peinture', 'alkyd', NULL, NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(73, 1, 'Terre de sienne naturelle', '1914552', NULL, NULL, 'peinture', 'alkyd', NULL, NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(74, 1, 'Phthalo green  (nuence jaune)   S1 PA', '1914521', NULL, NULL, 'peinture', 'alkyd', NULL, NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(75, 1, 'Teinte chair', '1914257', NULL, NULL, 'peinture', 'alkyd', NULL, NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(76, 2, 'Rust (Oxyde)', '73117', NULL, NULL, 'pigment', NULL, '35ml', NULL, NULL, NULL, 1, NULL, '2020-06-20 10:59:53', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(77, 2, 'Light Yellow Ochre', '73102', NULL, NULL, 'pigment', NULL, '35ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(78, 2, 'Dark Yellow Ochre', '73103', NULL, NULL, 'pigment', NULL, '35ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(79, 2, 'Natural Umber', '73109', NULL, NULL, 'pigment', NULL, '35ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(80, 2, 'Burnt Siena', '73106', NULL, NULL, 'pigment', NULL, '35ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(81, 2, 'Brown Iron Oxide', '73108', NULL, NULL, 'pigment', NULL, '35ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(82, 2, 'Natural Iron Oxide', '73115', NULL, NULL, 'pigment', NULL, '35ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(83, 2, 'Faded Olive Green', '73122', NULL, NULL, 'pigment', NULL, '35ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(84, 2, 'Dark Red Ochre', '73107', NULL, NULL, 'pigment', NULL, '35ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(85, 2, 'Dark rust', '76507', NULL, NULL, 'peinture', NULL, '35ml', 'wash', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(86, 2, 'Or liquide', '792', NULL, NULL, 'peinture', NULL, NULL, 'metal', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(87, 2, 'Russian Thick mud', '26808', NULL, NULL, 'peinture', 'acryl', NULL, 'thick mud', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(88, 2, 'Slimy Grime Light', '73823', NULL, NULL, 'peinture', 'acryl', '40ml', 'environment', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(89, 2, 'Mud And Grass', '73826', NULL, NULL, 'peinture', 'acryl', '40ml', 'environment', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(90, 2, 'Crushed Grass', '73825', NULL, NULL, 'peinture', 'acryl', '40ml', 'environment', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(91, 2, 'Pigment Binder', '26233', NULL, NULL, 'peinture', NULL, '30ml', 'divers', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(92, 2, 'Chipping Medium', '76550', NULL, NULL, 'peinture', NULL, '35ml', 'divers', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(93, 2, 'Magnesium', '77711', NULL, NULL, 'peinture', 'acryl', '32ml', 'metal', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(94, 2, 'Exaust escape', '77723', NULL, NULL, 'peinture', 'acryl', '32ml', 'metal', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(95, 2, 'White aluminium', '77706', NULL, NULL, 'peinture', 'acryl', '32ml', 'metal', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(96, 2, 'Chrome', '77707', NULL, NULL, 'peinture', 'acryl', '32ml', 'metal', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(97, 4, 'Bronze irridescent ', '3167869083548', '354 Série 3', NULL, 'peinture', 'acryl', '37ml', 'extra-fine', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(98, 4, 'Cuivre irridescent', '3167869083555', '355 Série 3', NULL, 'peinture', 'acryl', '37ml', 'extra-fine', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(99, 2, 'Desert Sand', '26217', NULL, NULL, 'peinture', 'acryl', '200ml', 'earth texture', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(100, 2, 'Russian Thick Mud', '26808', NULL, NULL, 'peinture', 'acryl', '200ml', 'acryl/alchool', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(101, 2, 'Rust & Chipping Effects', '71186', NULL, NULL, 'peinture', 'acryl', '17ml', NULL, 'air color', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(102, 2, 'Ochre', '71.033', NULL, NULL, 'peinture', 'acryl', '17ml', NULL, 'air color', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(103, 2, 'Camo Black Brown', '71.042', NULL, NULL, 'peinture', 'acryl', '17ml', NULL, 'air color', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(104, 2, 'Rost', '71.080', NULL, NULL, 'peinture', 'acryl', '17ml', NULL, 'air color', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(105, 2, 'Light Rust', '71.129', NULL, NULL, 'peinture', 'acryl', '17ml', NULL, 'air color', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(106, 2, 'Orange Rust', '71.130', NULL, NULL, 'peinture', 'acryl', '17ml', NULL, 'air color', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(107, 2, 'German Dark Red Brown RAL  8012 primer ', '70.605', NULL, NULL, 'peinture', 'acryl', '17ml', 'polyurethane', 'air color', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(108, 2, 'Chipping ?', '73.214', NULL, NULL, 'peinture', 'acryl', '17ml', NULL, 'air color', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(109, 2, 'Matt Varnish', '70.520', NULL, NULL, 'peinture', 'acryl', '17ml', NULL, 'air color', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(110, 3, 'Gloss Black Base ', 'ALC-305', NULL, NULL, 'peinture', 'lacquer', '120ml', 'metal', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(111, 3, 'Aluminuim', 'ALC-101', NULL, NULL, 'peinture', 'lacquer', '120ml', 'metal', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(112, 3, 'White Aluminium', 'ALC-106', NULL, NULL, 'peinture', 'lacquer', '120ml', 'metal', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(113, 3, 'Duraluminium', '', NULL, NULL, 'peinture', 'lacquer', '120ml', 'metal', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(114, 3, 'Jet Exhaust', 'ALC-113', NULL, NULL, 'peinture', 'lacquer', '120ml', 'metal', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(115, 3, 'Magnesium', 'ALC-111', NULL, NULL, 'peinture', 'lacquer', '120ml', 'metal', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(116, 3, 'Pale Gold', 'ALC-108', NULL, NULL, 'peinture', 'lacquer', '120ml', 'metal', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(117, 3, 'Chrome', 'ALC-107', NULL, NULL, 'peinture', 'lacquer', '120ml', 'metal', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(118, 3, 'Cobalt Blue', 'ALC-710', NULL, NULL, 'peinture', 'lacquer', '120ml', 'candy', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(119, 3, 'Emerald Green', 'ALC-708', NULL, NULL, 'peinture', 'lacquer', '120ml', 'candy', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(120, 3, 'Violet', 'ALC-712', NULL, NULL, 'peinture', 'lacquer', '120ml', 'candy', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(121, 3, 'Golden Yellow', 'ALC-706', NULL, NULL, 'peinture', 'lacquer', '120ml', 'candy', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(122, 3, 'Electric Blue', 'ALC-709', NULL, NULL, 'peinture', 'lacquer', '120ml', 'candy', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(123, 3, 'Bottle Green', 'ALC-707', NULL, NULL, 'peinture', 'lacquer', '120ml', 'candy', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(124, 3, 'Indigo', 'ALC-711', NULL, NULL, 'peinture', 'lacquer', '120ml', 'candy', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(125, 3, 'Lemon Yellow', 'ALC-705', NULL, NULL, 'peinture', 'lacquer', '120ml', 'candy', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(126, 3, 'Red', 'ALC-702', NULL, NULL, 'peinture', 'lacquer', '120ml', 'candy', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(127, 3, 'Ruby Red', 'ALC-703', NULL, NULL, 'peinture', 'lacquer', '120ml', 'candy', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(128, 3, 'Holomatic Spectral Chrome', 'ALC-205', NULL, NULL, 'peinture', 'lacquer', '120ml', 'metal', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(129, 7, 'RLM 02 Grau', NULL, 'A.MIG-217', NULL, 'peinture', 'acryl', '17ml', NULL, 'air set', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(130, 7, 'RLM 65 Hellblau', NULL, 'A.MIG-231', NULL, 'peinture', 'acryl', '17ml', NULL, 'air set', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(131, 7, 'RLM 70 Schartzgün', NULL, 'A.MIG-232', NULL, 'peinture', 'acryl', '17ml', NULL, 'air set', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(132, 7, 'RLM 71 Dunkelgrün', NULL, 'A.MIG-233', NULL, 'peinture', 'acryl', '17ml', NULL, 'air set', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(133, 7, 'Satin White', NULL, 'A.MIG-047', NULL, 'peinture', 'acryl', '17ml', NULL, 'air set', NULL, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(134, 7, 'FS33481 Zinc Chromatic Yellow', NULL, 'A.MIG-221', NULL, 'peinture', 'acryl', '17ml', NULL, 'air set', NULL, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(135, 7, 'FS35164 Interme.(ANA 608)', NULL, 'A.MIG-228', NULL, 'peinture', 'acryl', '17ml', NULL, 'air set', NULL, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(136, 7, 'FS25042 Sea Blue (ANA 606)', NULL, 'A.MIG-227', NULL, 'peinture', 'acryl', '17ml', NULL, 'air set', NULL, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(137, 7, 'DULL GREEN', NULL, 'A.MIG-077', NULL, 'peinture', 'acryl', '17ml', NULL, 'air set', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(138, 7, 'OCHRE EARTH', NULL, 'A.MIG-078', NULL, 'peinture', 'acryl', '17ml', NULL, 'air set', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(139, 7, 'CLAY BROWN', NULL, 'A.MIG-079', NULL, 'peinture', 'acryl', '17ml', NULL, 'air set', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(140, 7, 'GREY HIGH LIGHT', NULL, 'A.MIG-910', NULL, 'peinture', 'acryl', '17ml', NULL, 'air set', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(141, 7, 'LIGHT RUST', '8432074000396', 'A.MIG-039', NULL, 'peinture', 'acryl', '17ml', 'rusr effect', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(142, 7, 'MEDIUM RUST', '8432074000402', 'A.MIG-040', NULL, 'peinture', 'acryl', '17ml', 'rusr effect', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(143, 7, 'DARK RUST', '8432074000419', 'A.MIG-041', NULL, 'peinture', 'acryl', '17ml', 'rusr effect', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(144, 7, 'OLD RUST', '8432074000426', 'A.MIG-042', NULL, 'peinture', 'acryl', '17ml', 'rusr effect', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(145, 7, 'SHADOW RUST', '8432074000433', 'A.MIG-043', NULL, 'peinture', 'acryl', '17ml', 'rusr effect', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(146, 7, 'CHIPPING', '8432074000440', 'A.MIG-044', NULL, 'peinture', 'acryl', '17ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(147, 7, 'MATT BLACK (MS-17)', NULL, 'A.MIG-046', NULL, 'peinture', 'acryl', '17ml', NULL, NULL, NULL, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(148, 7, 'OIL OCHRE', NULL, 'A.MIG-055', NULL, 'peinture', 'acryl', '17ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(149, 7, 'GREEN KHAKI (KHS-5146)', NULL, 'A.MIG-056', NULL, 'peinture', 'acryl', '17ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(150, 7, 'YELLOW GREY (PKHV-4)', NULL, 'A.MIG-057', NULL, 'peinture', 'acryl', '17ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(151, 7, 'LIGHT GREEN KHAKI (PKHV-512)', NULL, 'A.MIG-058', NULL, 'peinture', 'acryl', '17ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(152, 7, 'GREY (KHV-16)', NULL, 'A.MIG-059', NULL, 'peinture', 'acryl', '17ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(153, 7, 'US MODERN VEHICLES', NULL, 'A.MIG-025', NULL, 'peinture', 'acryl', '17ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(154, 7, 'MATT BLACK (MS-17)', NULL, 'A.MIG-046', NULL, 'peinture', 'acryl', '17ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(155, 7, 'US OLIVE DRAB POST', NULL, 'A.MIG-081', NULL, 'peinture', 'acryl', '17ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(156, 7, 'US APC INTERIOR GREEN', NULL, 'A.MIG-082', NULL, 'peinture', 'acryl', '17ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(157, 7, 'NATO GREEN', NULL, 'A.MIG-084', NULL, 'peinture', 'acryl', '17ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(158, 7, 'NATO BROWN', NULL, 'A.MIG-085', NULL, 'peinture', 'acryl', '17ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(159, 7, 'FS36320 DARK COMPASS GHOST GREY', NULL, 'A.MIG-208', NULL, 'peinture', 'acryl', '17ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(160, 7, 'FS36270 MEDIUM GREY', NULL, 'A.MIG-211', NULL, 'peinture', 'acryl', '17ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(161, 7, 'FS36375 LIGHT COMPASS GHOST GREY', NULL, 'A.MIG-203', NULL, 'peinture', 'acryl', '17ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(162, 7, 'FS36118 MEDIUM GUNSHIP GRAY', NULL, 'A.MIG-204', NULL, 'peinture', 'acryl', '17ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(163, 7, '7K Russian tan', NULL, 'A.MIG-021', NULL, 'peinture', 'acryl', '17ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(164, 7, '6K Russian Brown', NULL, 'A.MIG-020', NULL, 'peinture', 'acryl', '17ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(165, 7, '4BO Russian Green', NULL, 'A.MIG-019', NULL, 'peinture', 'acryl', '17ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(166, 7, 'RAL 6003 Olivegrün Opt.2', 'A.MIG-002', 'A.MIG-002', NULL, 'peinture', 'acryl', '17ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(167, 7, 'RAL 7028 Dunkelgelb (M.W.)', NULL, 'A.MIG-010', NULL, 'peinture', 'acryl', '17ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(168, 7, 'RAL 8017 Schokobraun', NULL, 'A.MIG-015', NULL, 'peinture', 'acryl', '17ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(169, 7, 'Washable White Camo', NULL, 'A.MIG-024', NULL, 'peinture', 'acryl', '17ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(170, 7, 'Dark Tracks', NULL, 'A.MIG-035', NULL, 'peinture', 'acryl', '17ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(171, 7, 'New Wood', NULL, 'A.MIG-037', NULL, 'peinture', 'acryl', '17ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(172, 7, 'DARK GREEN', NULL, 'A.MIG-915', NULL, 'peinture', 'acryl', '17ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(173, 7, 'PROTECTIVE GREEN', NULL, 'A.MIG-023', NULL, 'peinture', 'acryl', '17ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(174, 7, 'PROTECTIVE NC 1200', NULL, 'A.MIG-053', NULL, 'peinture', 'acryl', '17ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(175, 7, '4BO Russian Green', NULL, 'A.MIG-019', NULL, 'peinture', 'acryl', '17ml', NULL, NULL, NULL, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(176, 7, 'ALKIDNO URETANOVAYA', NULL, 'A.MIG-022', NULL, 'peinture', 'acryl', '17ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(177, 7, 'Russian Green Base (ZIS 508)', NULL, 'A.MIG-932', NULL, 'peinture', 'acryl', NULL, NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(178, 7, 'Light Earth Ground', NULL, 'A.MIG-2102', NULL, 'peinture', 'acryl', '120ml', 'mud', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(179, 7, 'Muddy Ground', NULL, 'A.MIG-2105', NULL, 'peinture', 'acryl', '120ml', 'mud', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(180, 7, 'Medium Rust', NULL, 'A.MIG-3005', NULL, 'peinture', 'acryl', '35ml', 'pigment', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(181, 7, 'Light Rust', NULL, 'A.MIG-3006', NULL, 'peinture', 'acryl', '35ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(182, 7, 'North Africa Dust', NULL, 'A.MIG-3003', NULL, 'peinture', 'acryl', '35ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(183, 8, 'SAND YELLOW DEPOSIT', 'AK4061', NULL, NULL, 'peinture', 'enamel', '35ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(184, 8, 'LIGHT DUST DEPOSIT', 'AK4062', NULL, NULL, 'peinture', 'enamel', '35ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(185, 8, 'BROWN EARTH DEPOSIT', 'AK4063', NULL, NULL, 'peinture', 'enamel', '35ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(186, 8, 'FUEL STAINS', 'AK025', NULL, NULL, 'peinture', 'enamel', '35ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(187, 8, 'DECAY DEPOSITS', 'AK675', NULL, NULL, 'peinture', 'enamel', '35ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(188, 8, 'SUMMER KURSK EARTH', 'AK080', NULL, NULL, 'peinture', 'enamel', '35ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(189, 8, 'RAINMARKS for NATO TANKS', 'AK074', NULL, NULL, 'peinture', 'enamel', '35ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(190, 8, 'DUST EFFECTS', 'AK015', NULL, NULL, 'peinture', 'enamel', '35ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(191, 8, 'STREAKING GRIME', 'AK012', NULL, NULL, 'peinture', 'enamel', '35ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(192, 8, 'STREAKING GRIME for Panzer Grey', 'AK069', NULL, NULL, 'peinture', 'enamel', '35ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(193, 8, 'WINTER STREAKING GRIME', 'AK014', NULL, NULL, 'peinture', 'enamel', '35ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(194, 8, 'STREAKING GRIME for Dark Vehicles', 'AK067', NULL, NULL, 'peinture', 'enamel', '35ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(195, 8, 'DARK STREAKING GRIME', 'AK024', NULL, NULL, 'peinture', 'enamel', '35ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(196, 8, 'Blue for Panzer Grey', 'AK071', NULL, NULL, 'peinture', 'enamel', '35ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(197, 8, 'NEUTRAL GREY', 'AK4161', NULL, NULL, 'peinture', 'enamel', '35ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(198, 8, 'LIGHT BROWN FOR DESERT YELLOW', 'AK065', NULL, NULL, 'peinture', 'enamel', '35ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(199, 8, 'DARK BROWN FOR NATO AND GREEN', 'AK076', NULL, NULL, 'peinture', 'enamel', '35ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(200, 8, 'LIGHT RUST DEPOSITS', 'AK4111', NULL, NULL, 'peinture', 'enamel', '35ml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(201, 8, 'MEDIUM RUST DEPOSITS', 'AK4112', NULL, NULL, 'peinture', 'enamel', '35ml', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(202, 8, 'DARK RUST DEPOSIT', 'AK4113', NULL, NULL, 'peinture', 'enamel', '35ml', 'enamel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(203, 8, 'EARTH EFFECTS', 'AK017', NULL, NULL, 'peinture', 'enamel', '35ml', 'enamel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(204, 8, 'FRESH MUD', 'AK016', NULL, NULL, 'peinture', 'enamel', '35ml', 'enamel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(205, 8, 'DARK MUD', 'AK023', NULL, NULL, 'peinture', 'enamel', '35ml', 'enamel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(206, 8, 'DAMP EARTH', 'AK078', NULL, NULL, 'peinture', 'enamel', '35ml', 'enamel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(207, 8, 'TERRAINS NEUTRAL TEXTURE FOR EARTH', 'AK8023', NULL, NULL, 'peinture', 'enamel', '250ml', 'enamel', NULL, NULL, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(208, 8, 'TERRAINS SANDY DESERT', 'AK8022', NULL, NULL, 'peinture', 'enamel', '250ml', 'enamel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(209, 8, 'CORROSION TEXTURE', 'AK8040', NULL, NULL, 'peinture', 'enamel', '100ml', 'enamel', NULL, NULL, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(210, 8, 'SPLATTER EFFECTS WET MUD', 'AK8026', NULL, NULL, 'peinture', 'enamel', '100ml', 'enamel', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(211, 8, 'SPLATTER EFFECTS DRY MUD', 'AK8027', NULL, NULL, 'peinture', 'enamel', '100ml', 'enamel', NULL, NULL, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(212, 8, 'SPLATTER EFFECTS WET GROUND', 'AK8029', NULL, NULL, 'peinture', 'enamel', '100ml', 'enamel', NULL, NULL, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(213, 8, 'SPLATTER EFFECTS ACCUMULATED DUST', 'AK8031', NULL, NULL, 'peinture', 'enamel', '100ml', 'enamel', NULL, NULL, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(214, 8, 'LIGHT & DRY CRACKLE EFFECTS', 'AK8033', NULL, NULL, 'peinture', 'enamel', '100ml', 'cracle effect', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(215, 8, 'WET CRACKLE EFFECTS', 'AK8034', NULL, NULL, 'peinture', 'enamel', '100ml', 'cracle effect', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(216, 9, 'copper', '45035531', 'XF-6', NULL, 'peinture', 'acryl/alchool', '10ml', NULL, 'old', 'dilué', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(217, 9, 'derk yellow', '45035869', 'XF-60', NULL, 'peinture', 'acryl/alchool', '10ml', NULL, 'old', 'dilué', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(218, 9, 'olive green', '45035845', 'XF-58', NULL, 'peinture', 'acryl/alchool', '10ml', NULL, 'old', 'dilué', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(219, 9, 'J.A GREY', '49376340', 'XF-14', NULL, 'peinture', 'acryl/alchool', '23ml', NULL, 'old', 'dilué', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(220, 9, 'J.A GREEN', '49376333', 'XF-13', NULL, 'peinture', 'acryl/alchool', '23ml', NULL, 'old', 'dilué', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(221, 9, 'flat alluminium', '49376364', 'XF-16', NULL, 'peinture', 'acryl/alchool', '23ml', NULL, 'old', 'dilué', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(222, 14, 'interior green (sg)', '49372779', 'H58', NULL, 'peinture', 'acryl/alchool', '10ml', NULL, 'old', 'dilué', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(223, 14, 'flat red', NULL, 'H13', NULL, 'peinture', 'acryl/alchool', '10ml', NULL, 'old', 'dilué', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(224, 14, 'silver', '49372274', 'H8', NULL, 'peinture', 'acryl/alchool', '10ml', NULL, 'old', 'dilué', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(225, 14, 'khaki (m)', '49373004', 'H81', NULL, 'peinture', 'acryl/alchool', '10ml', NULL, 'old', 'dilué', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(226, 9, 'sky', '49376418', 'XF-21', NULL, 'peinture', 'acryl/alchool', '23ml', NULL, 'old', 'dilué', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(227, 9, 'buff', '49376579', 'XF-57', NULL, 'peinture', 'acryl/alchool', '23ml', NULL, 'old', 'dilué', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(228, 9, 'medium grey', '49376302', 'XF-20', NULL, 'peinture', 'acryl/alchool', '23ml', NULL, 'old', 'dilué', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(229, 9, 'flet red', '49376272', 'XF-7', NULL, 'peinture', 'acryl/alchool', '23ml', NULL, 'old', 'dilué', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(230, 9, 'deck tan', '49376555', 'XF-55', NULL, 'peinture', 'acryl/alchool', '23ml', NULL, 'old', 'dilué', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(231, 9, 'flat red', '45035548', 'XF-7', NULL, 'peinture', 'acryl/alchool', '10ml', NULL, 'old', 'dilué', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(232, 5, 'EVIL SUNZ SCARLET', NULL, NULL, NULL, 'peinture', 'acryl', '12ml', 'layer', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(233, 5, 'KHRONE RED', NULL, NULL, NULL, 'peinture', 'acryl', '12ml', 'base', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(234, 5, 'MEPHISTON RED', NULL, NULL, NULL, 'peinture', 'acryl', '12ml', 'base', NULL, NULL, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(235, 5, 'FLASH GITZ YELLOW', NULL, NULL, NULL, 'peinture', 'acryl', '12ml', 'layer', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(236, 5, 'TALLARN', NULL, NULL, NULL, 'peinture', 'acryl', '12ml', 'layer', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(237, 5, 'GUILLIMAN BLUE', NULL, NULL, NULL, 'peinture', 'acryl', '12ml', 'glaze', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(238, 5, 'AVERLAND SUNSET', NULL, NULL, NULL, 'peinture', 'acryl', '12ml', 'base', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(239, 5, 'TEMPLE GUARD BLUE', NULL, NULL, NULL, 'peinture', 'acryl', '12ml', 'layer', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(240, 5, 'STEGADON SCALE GREEN', NULL, NULL, NULL, 'peinture', 'acryl', '12ml', 'base', NULL, NULL, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(241, 5, 'LOREN FOREST', NULL, NULL, NULL, 'peinture', 'acryl', '12ml', 'layer', NULL, NULL, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(242, 5, 'MACRAGGE BLUE', NULL, NULL, NULL, 'peinture', 'acryl', '12ml', 'base', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(243, 5, 'XEREUS PURPLE', NULL, NULL, NULL, 'peinture', 'acryl', '12ml', 'layer', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(244, 5, 'SYBARITE GREEN', NULL, NULL, NULL, 'peinture', 'acryl', '12ml', 'layer', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(245, 5, 'SUNBURST YELLOW', NULL, NULL, NULL, 'peinture', 'acryl', '12ml', 'base ?', 'old', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(246, 5, 'SRORM BLUE', NULL, NULL, NULL, 'peinture', 'acryl', '12ml', 'base ?', 'old', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(247, 5, 'BLOOD RED', NULL, NULL, NULL, 'peinture', 'acryl', '12ml', 'base ?', 'old', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(248, 5, 'ENCHANTED BLUE', NULL, NULL, NULL, 'peinture', 'acryl', '12ml', 'base ?', 'old', NULL, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(249, 5, 'TERRACOTTA', NULL, NULL, NULL, 'peinture', 'acryl', '12ml', 'base ?', 'old', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(250, 5, 'DWARF FLESH', NULL, NULL, NULL, 'peinture', 'acryl', '12ml', 'base ?', 'old', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(251, 5, 'SKULL WHITE', NULL, NULL, NULL, 'peinture', 'acryl', '12ml', 'base ?', 'old', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(252, 5, 'KOMMANDO KHAKI', NULL, NULL, NULL, 'peinture', 'acryl', '12ml', 'base ?', 'old', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(253, 5, 'DESSERT YELLOW', NULL, NULL, NULL, 'peinture', 'acryl', '12ml', 'base ?', 'old', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(254, 5, 'BAD MOON YELLOW', NULL, NULL, NULL, 'peinture', 'acryl', '12ml', 'base ?', 'old', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(255, 5, 'CHAOS BLACK', NULL, NULL, NULL, 'peinture', 'acryl', '12ml', 'base ?', 'old', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(256, 5, 'GRAVEYARD EARTH', NULL, NULL, NULL, 'peinture', 'acryl', '12ml', 'base ?', 'old', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(257, 9, 'CLEAR', NULL, 'X-22', NULL, 'peinture', 'acryl/alchool', '10ml', NULL, NULL, NULL, 1, NULL, NULL, '2020-05-23 12:08:50', NULL, NULL, NULL, NULL, NULL, NULL),
	(258, 15, 'qsdqsdqsdsq', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', NULL, NULL, NULL, NULL, '2020-05-23 12:21:04', NULL, NULL, NULL, NULL, NULL, NULL),
	(259, 15, 'qsdqsdqsdsq', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', NULL, NULL, NULL, NULL, '2020-05-23 12:22:34', NULL, NULL, NULL, NULL, NULL, NULL),
	(260, 15, 'qsdqsdqsdsq', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', NULL, NULL, NULL, NULL, '2020-05-23 12:22:50', NULL, NULL, NULL, NULL, NULL, NULL),
	(261, 15, 'ff', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'dddd', NULL, NULL, NULL, NULL, '2020-05-23 12:23:06', NULL, NULL, NULL, NULL, NULL, NULL),
	(262, 9, 'DESERT YELLOW', NULL, 'XF-59', NULL, 'peinture', 'acryl/alchool', '10ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(263, 9, 'GERMAN GREY', NULL, 'XF-63', NULL, 'peinture', 'acryl/alchool', '10ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(264, 9, 'DARK GREEN', NULL, 'XF-61', NULL, 'peinture', 'acryl/alchool', '10ml', NULL, NULL, NULL, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(265, 9, 'RED BROWN 2', NULL, 'XF-90', NULL, 'peinture', 'acryl/alchool', '10ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(266, 9, 'FIELD GREY', NULL, 'XF-65', NULL, 'peinture', 'acryl/alchool', '10ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(267, 9, 'RED BROWN', NULL, 'XF-64', NULL, 'peinture', 'acryl/alchool', '10ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(268, 9, 'MEDIUM BLUE', NULL, 'XF-18', NULL, 'peinture', 'acryl/alchool', '10ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(269, 5, 'AGRAX EARTHSHADE', NULL, NULL, NULL, 'peinture', 'acryl', '24ml', 'shade', NULL, 'gloss', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(270, 5, 'NULN OIL', NULL, NULL, NULL, 'peinture', 'acryl', '24ml', 'shade', NULL, 'gloss', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(271, 5, 'CALIBAN GREEN', NULL, NULL, NULL, 'peinture', 'acryl', '12ml', 'base', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(272, 5, 'MOOT GREEN', NULL, NULL, NULL, 'peinture', 'acryl', '12ml', 'layer', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(273, 5, 'WARPSTONE GLOW', NULL, NULL, NULL, 'peinture', 'acryl', '12ml', 'layer', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(274, 5, 'CAMO GREEN', NULL, NULL, NULL, 'peinture', 'acryl', '12ml', 'base ?', 'old', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(275, 5, 'YRIEL YELLOW', NULL, NULL, NULL, 'peinture', 'acryl', '12ml', 'layer', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(276, 5, 'KANTOR BLUE', NULL, NULL, NULL, 'peinture', 'acryl', '12ml', 'base', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(277, 5, 'KISLEV FLESH', NULL, NULL, NULL, 'peinture', 'acryl', '12ml', 'layer', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(278, 5, 'PALLID WYCH FLESH', NULL, NULL, NULL, 'peinture', 'acryl', '12ml', 'layer', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(279, 5, 'AURIC ARMOUR GOLD', NULL, NULL, NULL, 'peinture', 'acryl', '12ml', 'layer', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(280, 5, 'SYCORAX BRONZE', NULL, NULL, NULL, 'peinture', 'acryl', '12ml', 'layer', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(281, 5, 'CERAMITE WHITE', NULL, NULL, NULL, 'peinture', 'acryl', '12ml', 'base', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(282, 5, 'TECLIS BLUE', NULL, NULL, NULL, 'peinture', 'acryl', '12ml', 'layer', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(283, 5, 'ABADDON BLACK', NULL, NULL, NULL, 'peinture', 'acryl', '12ml', 'base', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(284, 5, 'SCREAMER PINK', NULL, NULL, NULL, 'peinture', 'acryl', '12ml', 'base', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(285, 5, 'WAZDAKKA RED', NULL, NULL, NULL, 'peinture', 'acryl', '12ml', 'layer', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(286, 5, 'PINK HORROR', NULL, NULL, NULL, 'peinture', 'acryl', '12ml', 'layer', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(287, 5, 'BUGMAN\'S GLOW', NULL, NULL, NULL, 'peinture', 'acryl', '12ml', 'base', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(288, 5, 'MECHANICUS STANDARD GREY', NULL, NULL, NULL, 'peinture', 'acryl', '12ml', 'base', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(289, 5, 'THUNDERHAWK BLUE', NULL, NULL, NULL, 'peinture', 'acryl', '12ml', 'layer', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(290, 5, 'FENRISIAN GREY', NULL, NULL, NULL, 'peinture', 'acryl', '12ml', 'layer', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(291, 5, 'ADMINISTRATUM GREY', NULL, NULL, NULL, 'peinture', 'acryl', '12ml', 'layer', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(292, 5, 'REIKLAND FRESHSHADE', NULL, NULL, NULL, 'peinture', 'acryl', '12ml', 'shade', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(293, 5, 'ARDCOAT', NULL, NULL, NULL, 'peinture', 'acryl', '12ml', 'technical', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(294, 8, 'ALUMINIUM', 'AK455', NULL, NULL, 'peinture', 'true metal', NULL, 'cire', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(295, 8, 'GUN METAL', 'AK461', NULL, NULL, 'peinture', 'true metal', NULL, 'cire', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(296, 8, 'SILVER', 'AK458', NULL, NULL, 'peinture', 'true metal', NULL, 'cire', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(297, 8, 'IRON', 'AK459', NULL, NULL, 'peinture', 'true metal', NULL, 'cire', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(298, 8, 'DARL ALUMINIUM', 'AK456', NULL, NULL, 'peinture', 'true metal', NULL, 'cire', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(299, 8, 'BURNT METAL', 'AK484', NULL, NULL, 'peinture', 'lacque', '30ml', 'xtreme metal', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(300, 8, 'GUN METAL', 'AK483', NULL, NULL, 'peinture', 'lacque', '30ml', 'xtreme metal', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(301, 8, 'DURALUMINIUM', 'AK482', NULL, NULL, 'peinture', 'lacque', '30ml', 'xtreme metal', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(302, 8, 'STEEL', 'AK476', NULL, NULL, 'peinture', 'lacque', '30ml', 'xtreme metal', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(303, 8, 'BRASS', 'AK475', NULL, NULL, 'peinture', 'lacque', NULL, 'xtreme metal', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(304, 8, 'BLACK BASE', 'AK471', NULL, NULL, 'peinture', 'lacque', NULL, 'xtreme metal', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(305, 8, 'WHITE ALUMINIUM', 'AK478', NULL, NULL, 'peinture', 'lacque', NULL, 'xtreme metal', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(306, 8, 'CHROME', 'AK477', NULL, NULL, 'peinture', 'lacque', NULL, 'xtreme metal', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(307, 8, 'BRONZE', 'AK474', NULL, NULL, 'peinture', 'lacque', NULL, 'xtreme metal', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(308, 8, 'COPPER', 'AK473', NULL, NULL, 'peinture', 'lacque', NULL, 'xtreme metal', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(309, 8, 'POLISHED ALUMINIUM', 'AK481', NULL, NULL, 'peinture', 'lacque', NULL, 'xtreme metal', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(310, 8, 'GOLD', 'AK472', NULL, NULL, 'peinture', 'lacque', NULL, 'xtreme metal', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(311, 5, 'AVERLAND SUNSET', NULL, NULL, NULL, 'peinture', 'acryl', '12ml', 'base', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(312, 5, 'MOURNFANG BROWN', NULL, NULL, NULL, 'peinture', 'acryl', '12ml', 'base', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(313, 5, 'RAKARTH FLESH', NULL, NULL, NULL, 'peinture', 'acryl', '12ml', 'base', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(314, 5, 'CASANDORA YELLOW', NULL, NULL, NULL, 'peinture', 'acryl', '24ml', 'shade', NULL, 'gloss', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(315, 5, 'AETHERMATIC BLUE', NULL, NULL, NULL, 'peinture', 'acryl', '18ml', 'contrast', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(316, 5, 'TALASSAR BLUE', NULL, NULL, NULL, 'peinture', 'acryl', '18ml', 'contrast', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(317, 5, 'BLOOD ANGELS RED', NULL, NULL, NULL, 'peinture', 'acryl', '18ml', 'contrast', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(318, 5, 'DOOMBULL BROWN', NULL, NULL, NULL, 'peinture', 'acryl', '12ml', 'layer', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(319, 5, 'CELESTRA GREY', NULL, NULL, NULL, 'peinture', 'acryl', '12ml', 'base', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(320, 5, 'WAAAGH! FLESH', NULL, NULL, NULL, 'peinture', 'acryl', '12ml', 'base', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(321, 5, 'PHOENICIAN PURPLE', NULL, NULL, NULL, 'peinture', 'acryl', '12ml', 'base', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(322, 5, 'THE FANG', NULL, NULL, NULL, 'peinture', 'acryl', '12ml', 'base', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(323, 5, 'THOUSAND SONS BLUE', NULL, NULL, NULL, 'peinture', 'acryl', '12ml', 'base', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(324, 5, 'TUSKGOR FUR', NULL, NULL, NULL, 'peinture', 'acryl', '12ml', 'layer', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(325, 5, 'CALEDOR SKY', NULL, NULL, NULL, 'peinture', 'acryl', '12ml', 'base', NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(326, 6, 'Fluor Pigments Yellow', '2366', NULL, NULL, 'peinture', 'pigment', '30ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, 3.95, NULL, NULL, NULL, NULL, NULL),
	(327, 6, 'Fluor Pigments Red', '2369', NULL, NULL, 'peinture', 'pigment', '30ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, 3.95, NULL, NULL, NULL, NULL, NULL),
	(328, 6, 'Fluor Pigments Blue', '2371', NULL, NULL, 'peinture', 'pigment', '30ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, 3.95, NULL, NULL, NULL, NULL, NULL),
	(329, 6, 'Fluor Pigments White', '2377', NULL, NULL, 'peinture', 'pigment', '30ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, 3.95, NULL, NULL, NULL, NULL, NULL),
	(330, 6, 'HYDROMEL YELLOW', '1723', NULL, NULL, 'peinture', 'intensity ink', '17ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, 2.69, NULL, NULL, NULL, NULL, NULL),
	(331, 6, 'TENEBRIS BLUE', '1732', NULL, NULL, 'peinture', 'intensity ink', '17ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, 2.69, NULL, NULL, NULL, NULL, NULL),
	(332, 6, 'SANGUINEM RED ', '1725', NULL, NULL, 'peinture', 'intensity ink', '17ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, 2.69, NULL, NULL, NULL, NULL, NULL),
	(333, 6, 'CITRINE YELLOW', '1759', NULL, NULL, 'peinture', 'candy ink', '17ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, 2.69, NULL, NULL, NULL, NULL, NULL),
	(334, 6, 'RUBY RED', '1756', NULL, NULL, 'peinture', 'candy ink', '17ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, 2.69, NULL, NULL, NULL, NULL, NULL),
	(335, 6, 'AMBER ORANGE', '1726', NULL, NULL, 'peinture', 'candy ink', '17ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, 2.69, NULL, NULL, NULL, NULL, NULL),
	(336, 6, 'SAPPHIRE BLUE', '1739', NULL, NULL, 'peinture', 'candy ink', '17ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, 2.69, NULL, NULL, NULL, NULL, NULL),
	(337, 6, 'FLUORESCENT YELLOW / AMARILLO', '1701', NULL, NULL, 'peinture', 'fluor', '17ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, 2.69, NULL, NULL, NULL, NULL, NULL),
	(338, 6, 'FLUORESCENT RED / ROJO', '1704', NULL, NULL, 'peinture', 'fluor', '17ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, 2.69, NULL, NULL, NULL, NULL, NULL),
	(339, 6, 'FLUORESCENT BLUE / AZUL', '1707', NULL, NULL, 'peinture', 'fluor', '17ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, 2.69, NULL, NULL, NULL, NULL, NULL),
	(340, 6, 'Fluor Pigments Green Lime', '2364', NULL, NULL, 'peinture', 'pigment', '30ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, 3.95, NULL, NULL, NULL, NULL, NULL),
	(341, 6, 'Fluor Pigments Pink', '2368', NULL, NULL, 'peinture', 'pigment', '30ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, 3.95, NULL, NULL, NULL, NULL, NULL),
	(342, 6, 'Fluor Pigments Purple', '2370', NULL, NULL, 'peinture', 'pigment', '30ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, 3.95, NULL, NULL, NULL, NULL, NULL),
	(343, 6, 'AMETHYST PURPLE', '1738', NULL, NULL, 'peinture', 'candy ink', '17ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, 2.69, NULL, NULL, NULL, NULL, NULL),
	(344, 6, 'QUARTZ MAGENTA', '1757', NULL, NULL, 'peinture', 'candy ink', '17ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, 2.69, NULL, NULL, NULL, NULL, NULL),
	(345, 6, 'STEAMPUNK COPPER', '1868', NULL, NULL, 'peinture', 'metal color', '17ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(346, 6, 'PAINT REVITALIZER', '1750', NULL, NULL, 'peinture', 'tools', '60ml', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(347, 6, 'AUTUMN LEAF LITTER', '1264', NULL, NULL, 'leaf litter', 'tools', NULL, NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(348, 15, 'ORRUK MEGABOSS', NULL, NULL, 'sfssfdsdf', 'figurine', 'warhammer', 'age of sigmar', 'ironjawz', NULL, NULL, 1, 'megaboss.webp', NULL, '2021-03-13 16:46:27', 29.5, NULL, NULL, NULL, '5011921070251', 1),
	(349, 15, 'SEQUITORS', NULL, NULL, '3 figurines ', 'figurine', 'warhammer', 'age of sigmar', 'stormcast eternals', '3 fig', 'easy to build', 1, 'sequitors.webp', NULL, '2021-03-13 16:46:27', 11, NULL, NULL, NULL, '5011921099320', 1),
	(350, 15, 'SEQUITORS', NULL, NULL, '10 figurines', 'figurine', 'warhammer', 'age of sigmar', 'stormcast eternals', '10 fig', NULL, 1, NULL, NULL, '2021-03-13 16:46:27', 45, NULL, NULL, NULL, '5011921104642', 1),
	(351, 15, 'DREADBLADE HARROWS', NULL, NULL, '2 figurines', 'figurine', 'warhammer', 'age of sigmar', 'nightaunt', '2 fig', 'easy to build', 1, NULL, NULL, '2021-03-13 16:46:27', 18, NULL, NULL, NULL, '5011921100903', 1),
	(352, 15, 'CELESTINE THE LIVING SAINT', NULL, NULL, '3 figurines ', 'figurine', 'warhammer', 'warhammer 40000', 'adepta sororitas', '3 fig', NULL, 1, NULL, NULL, '2021-03-13 16:46:27', 38, NULL, NULL, NULL, '5011921088638', 1),
	(353, 15, 'BATTLE SISTERS SQUAD', NULL, NULL, '11 figurines', 'figurine', 'warhammer', 'warhammer 40000', 'adepta sororitas', '11 fig', NULL, 1, NULL, NULL, '2021-03-13 16:46:27', 40.5, NULL, NULL, NULL, '5011921131167', 1),
	(354, 15, 'SIGVALD prince of slaanesh', NULL, NULL, '1 figurine', 'figurine', 'warhammer', 'age of sigmar', 'hedonites of slaanesh', '1 fig', NULL, 1, NULL, NULL, '2021-03-13 16:46:27', 38.5, NULL, NULL, NULL, '5011921128112', 1),
	(355, 15, 'NECRON IMMORTALS', NULL, NULL, '5 figurines', 'figurine', 'warhammer', 'warhammer 40000', 'necrons', '5 fig', NULL, 1, NULL, NULL, '2021-03-13 16:46:27', NULL, NULL, NULL, NULL, '5011921092239', 1),
	(356, 15, 'PALADINS', NULL, NULL, '5 figurines', 'figurine', 'warhammer', 'age of sigmar', 'stormcast eternals', '5 fig', NULL, 1, NULL, NULL, '2021-03-13 16:46:27', NULL, NULL, NULL, NULL, '5011921061198', 1),
	(357, 15, 'VARANGUARD', NULL, NULL, '3 figurines ', 'figurine', 'warhammer', 'age of sigmar', 'knights of ruin', '3 fig', NULL, 1, NULL, NULL, '2021-03-13 16:46:27', NULL, NULL, NULL, NULL, '5011921066797', 1),
	(358, 15, 'LORD OH VIRULENCE', NULL, NULL, '1 figurine', 'figurine', 'warhammer', 'warhammer 40000', 'death guard', '1 fig', NULL, 1, NULL, NULL, '2021-03-13 16:46:27', NULL, NULL, NULL, NULL, '5011921138876', 1),
	(359, 15, 'DRYCHA HAMADRETH', NULL, NULL, '1 figurine', 'figurine', 'warhammer', 'age of sigmar', 'sylvaneth', '1 fig', NULL, 1, NULL, NULL, '2021-03-13 16:46:27', NULL, NULL, NULL, NULL, '5011921073665', 1),
	(360, 15, 'ORRUK ARDBOYS', NULL, NULL, '15 figurines', 'figurine', 'warhammer', 'age of sigmar', 'ironjawz', '15 fig', NULL, 1, NULL, NULL, '2021-03-13 16:46:27', NULL, NULL, NULL, NULL, '501192107305', 1),
	(361, 15, 'TRIARCH STALKER', NULL, NULL, '1 figurine', 'figurine', 'warhammer', 'warhammer 40000', 'necrons', '1 fig', NULL, 1, NULL, NULL, '2021-03-13 16:46:27', NULL, NULL, NULL, NULL, '5011921139170', 1),
	(362, 15, 'SKORPEKH DESTROYERS', NULL, NULL, '4 figurines', 'figurine', 'warhammer', 'warhammer 40000', 'necrons', '4 fig', NULL, 1, NULL, NULL, '2021-03-13 16:46:27', NULL, NULL, NULL, NULL, '5011921138586', 1),
	(363, 15, 'ILLUMINOR SZERAS', NULL, NULL, '1 figurine', 'figurine', 'warhammer', 'warhammer 40000', 'necrons', '1 fig', NULL, 1, NULL, NULL, '2021-03-13 16:46:27', 36, NULL, NULL, NULL, '5011921136964', 1),
	(364, 15, 'ARKHAN THE BLACK', NULL, NULL, '1 figurine', 'figurine', 'warhammer', 'age of sigmar', 'mortarchs of nagash ', '1 fig', NULL, 1, NULL, NULL, '2021-03-13 16:46:27', NULL, NULL, NULL, NULL, '5011921054275', 1),
	(365, 15, 'MAGMIC INVOCATIONS', NULL, NULL, '3 figurines', 'figurine', 'warhammer', 'age of sigmar', 'fyreslayers', '3 fig', NULL, 1, NULL, NULL, '2021-03-13 16:46:27', NULL, NULL, NULL, NULL, '5011921118274', 1),
	(366, 15, 'NIGHTHAUNT', NULL, NULL, '14 figurines', 'figurine', 'warhammer', 'age of sigmar', 'warcry', '14 fig', NULL, 1, NULL, NULL, '2021-03-13 16:46:27', NULL, NULL, NULL, NULL, '5011921121656', 1),
	(367, 15, 'ORK DEFF DREAD', NULL, NULL, '1 figurine', 'figurine', 'warhammer', 'warhammer 40000', NULL, '1 fig', NULL, 1, NULL, NULL, '2021-03-13 16:46:27', NULL, NULL, NULL, NULL, '5011921018352', 1),
	(368, 15, 'BEASTCLAW RAIDERS', NULL, NULL, '5 figurines', 'figurine', 'warhammer', 'age of sigmar', NULL, '5 fig', 'start collecting', 1, NULL, NULL, '2021-03-13 16:46:27', 63, NULL, NULL, NULL, '5011921088188', 1),
	(369, 15, 'MAGNUS THE RED', NULL, NULL, '1 figurine. Daemon primarch of tzeentch', 'figurine', 'warhammer', 'warhammer 40000', 'thousans sons', '1 fig', NULL, 1, NULL, NULL, '2021-03-13 16:46:27', NULL, NULL, NULL, NULL, '5011921079513', 1),
	(370, 15, 'STORMCAST ETERNALS', NULL, NULL, '11 figurines', 'figurine', 'warhammer', 'age of sigmar', NULL, '11 fig', 'start collecting', 1, NULL, NULL, '2021-03-13 16:46:27', NULL, NULL, NULL, NULL, '5011921071890', 1),
	(371, 15, 'DRACOTHIAN GUARD', NULL, NULL, 'lord-celestant on dracoth, dracothian guard concussor, tempestors', 'figurine', 'warhammer', 'age of sigmar', 'stormcast eternal', '2 fig', NULL, 1, NULL, NULL, '2021-03-13 16:46:27', NULL, NULL, NULL, NULL, '5011921069736', 1),
	(372, 15, 'JUDICATOR', NULL, NULL, '10 figurines', 'figurine', 'warhammer', 'age of sigmar', 'stormcast eternal', '10 fig', NULL, 1, NULL, NULL, '2021-03-13 16:46:27', NULL, NULL, NULL, NULL, '5011921079278', 1),
	(373, 15, 'NECRON TRIARCH PRAETORIANS', NULL, NULL, '5 figurines', 'figurine', 'warhammer', 'warhammer 40000', 'necron', '5 fig', NULL, 1, NULL, NULL, '2021-03-13 16:46:27', NULL, NULL, NULL, NULL, '5011921028061', 1),
	(374, 15, 'IMPERIAL KNIGHTS', NULL, NULL, '3 figurines', 'figurine', 'warhammer', 'warhammer 40000', 'adeptus titanicus', '3 fig', NULL, 1, NULL, NULL, '2021-03-13 16:46:27', NULL, NULL, NULL, NULL, '5011921103591', 1),
	(375, 15, 'HELDRAKE', NULL, NULL, '1 figurine', 'figurine', 'warhammer', 'warhammer 40000', 'chaos space marines', '1 fig', NULL, 1, NULL, NULL, '2021-03-13 16:46:27', NULL, NULL, NULL, NULL, '5011921079018', 1),
	(376, 15, 'FLESH-EATER COURTS', NULL, NULL, '14 figurines', 'figurine', 'warhammer', 'age of sigmar', 'crypt horror, crypt ghouls, abhorrant ghoul king on terrorgheist', '14 fig', NULL, 1, NULL, NULL, '2021-03-13 16:46:27', NULL, NULL, NULL, NULL, '5011921076628', 1),
	(377, 15, 'IRONCLAD DREADNOUGHT', NULL, NULL, '1 figurine', 'figurine', 'warhammer', 'warhammer 40000', 'space marines', '1 fig', NULL, 1, NULL, NULL, '2021-03-13 16:46:27', NULL, NULL, NULL, NULL, '5011921015986', 1),
	(378, 15, 'NECRON CATACOMB COMMAND BARGE', NULL, NULL, '1 figurine', 'figurine', 'warhammer', 'warhammer 40000', 'necron', '1 fig', NULL, 1, NULL, NULL, '2021-03-13 16:46:27', NULL, NULL, NULL, NULL, '5011921028078', 1),
	(379, 16, 'KHALGRIM GUNNARSON', 'SCF-007', NULL, '1 figurine', 'figurine', 'scale word fantasy', '75 mm', NULL, '1 fig', '75 mm', 1, NULL, NULL, '2021-03-13 16:46:27', NULL, NULL, NULL, NULL, NULL, NULL),
	(380, 17, 'BUST EXCELSY', NULL, NULL, '1 figurine', 'figurine', NULL, '1/12', NULL, NULL, NULL, 1, NULL, NULL, '2021-03-13 16:46:27', NULL, NULL, NULL, NULL, NULL, NULL),
	(381, 15, 'LORD-AQUILOR', NULL, NULL, '1 figurine', 'figurine', 'warhammer', 'age of sigmar', 'stormcast eternal', '1 fig', NULL, 1, NULL, NULL, '2021-03-13 16:46:27', 29.5, NULL, NULL, NULL, '5011921082926', 1),
	(382, 15, 'TRAJANN VALORIS (CAPTAIN-GENERAL)', NULL, NULL, '1 figurine', 'figurine', 'warhammer', 'warhammer 40000', 'adeptus custodes', '1 fig', 'heroic champion of the emperor\'s guard ; watcher\'s axe', 1, NULL, NULL, '2021-03-13 16:46:27', 29.5, NULL, NULL, NULL, '5011921094219', 1),
	(383, 15, 'CUSTODIAN WARDENS', NULL, NULL, '1 figurine', 'figurine', 'warhammer', 'warhammer 40000', 'adeptus custodes', '5 fig', NULL, 1, NULL, NULL, '2021-03-13 16:46:27', 40.5, NULL, NULL, NULL, '5011921094226', 1),
	(384, 15, 'BLADEGUARD VETERANS', NULL, NULL, '3 figurines', 'figurine', 'warhammer', 'warhammer 40000', 'space marines', '3 fig', NULL, 1, NULL, NULL, '2021-03-13 16:46:27', 36, NULL, NULL, NULL, '5011921138630', 1);
/*!40000 ALTER TABLE `article` ENABLE KEYS */;

-- Listage de la structure de la table hobby. departement
CREATE TABLE IF NOT EXISTS `departement` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `region_id` int(11) NOT NULL,
  `nom` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  KEY `IDX_C1765B6398260155` (`region_id`) USING BTREE,
  CONSTRAINT `FK_C1765B6398260155` FOREIGN KEY (`region_id`) REFERENCES `region` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPACT;

-- Listage des données de la table hobby.departement : ~4 rows (environ)
DELETE FROM `departement`;
/*!40000 ALTER TABLE `departement` DISABLE KEYS */;
INSERT INTO `departement` (`id`, `region_id`, `nom`) VALUES
	(1, 1, 'dep1 aaaa aaaaaaaa'),
	(2, 2, 'dep2'),
	(3, 2, 'dep3\r\n                                                             '),
	(4, 1, 'dep2');
/*!40000 ALTER TABLE `departement` ENABLE KEYS */;

-- Listage de la structure de la table hobby. marque
CREATE TABLE IF NOT EXISTS `marque` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nom` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  `created_by` int(11) NOT NULL,
  `updated_by` int(11) DEFAULT NULL,
  `deleted_by` int(11) DEFAULT NULL,
  `tag1` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tag2` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tag3` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tag4` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tag5` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ville_id` int(11) DEFAULT NULL,
  `filename` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  KEY `IDX_5A6F91CEA73F0036` (`ville_id`) USING BTREE,
  CONSTRAINT `FK_5A6F91CEA73F0036` FOREIGN KEY (`ville_id`) REFERENCES `ville` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=18 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPACT;

-- Listage des données de la table hobby.marque : ~17 rows (environ)
DELETE FROM `marque`;
/*!40000 ALTER TABLE `marque` DISABLE KEYS */;
INSERT INTO `marque` (`id`, `nom`, `description`, `created_at`, `updated_at`, `deleted_at`, `created_by`, `updated_by`, `deleted_by`, `tag1`, `tag2`, `tag3`, `tag4`, `tag5`, `ville_id`, `filename`) VALUES
	(1, 'W&N', 'Winsor & Newton', '2014-01-01 00:00:00', '2020-06-06 04:01:53', NULL, 2, NULL, NULL, 'arts graphiques', NULL, NULL, NULL, NULL, 1, 'wn.jpg'),
	(2, 'Vallejo', NULL, '2019-12-02 21:16:51', '2020-06-06 04:02:54', NULL, 0, NULL, NULL, 'peinture', NULL, NULL, NULL, NULL, 1, 'valejjo.png'),
	(3, 'ALCLAD2', NULL, '2019-12-02 21:26:42', '2019-12-03 21:48:20', NULL, 0, NULL, NULL, 'peinture', NULL, NULL, NULL, NULL, 1, NULL),
	(4, 'Pébéo', NULL, '2019-12-02 21:40:18', '2020-06-06 04:01:07', NULL, 0, NULL, NULL, 'arts graphiques', NULL, NULL, NULL, NULL, 1, 'pebeo.jpg'),
	(5, 'CITADEL', 'marque de peinture', '2019-12-02 21:40:32', '2020-06-06 03:57:18', NULL, 0, NULL, NULL, 'peinture', NULL, NULL, NULL, NULL, 1, 'citadel.jpg'),
	(6, 'GSW', 'Green Stuff World', '2019-12-03 21:58:46', '2019-12-03 21:58:46', NULL, 0, NULL, NULL, 'modelisme', NULL, NULL, NULL, NULL, 1, NULL),
	(7, 'MIG', 'mig (ammo) Jimenez', '2019-12-08 17:06:02', '2020-05-22 09:25:43', NULL, 0, NULL, NULL, 'modelisme', 'maquette', 'livre', 'fourniture', NULL, 1, 'mig.jpg'),
	(8, 'AK', 'AK interactive', '2019-12-08 17:06:24', '2020-05-22 09:32:40', NULL, 0, NULL, NULL, 'modelisme', 'maquettes', 'livre', 'fourniture', NULL, 1, 'ak.png'),
	(9, 'TAMIYA', NULL, '2019-12-08 17:09:42', '2020-05-22 09:33:08', NULL, 0, NULL, NULL, 'modelisme', 'maquettes', 'livre', 'fourniture', NULL, 1, 'tamiya.png'),
	(10, 'TRUMPETER', NULL, '2019-12-08 17:10:05', NULL, NULL, 0, NULL, NULL, 'modelisme', 'maquettes', NULL, NULL, NULL, 1, 'trumpeter.jfif'),
	(11, 'TAKOM', NULL, '2019-12-08 17:10:23', NULL, NULL, 0, NULL, NULL, 'modelisme', 'maquettes', NULL, NULL, NULL, 1, 'takom.png'),
	(12, 'ITALERI', NULL, '2019-12-08 17:10:39', NULL, NULL, 0, NULL, NULL, 'modelisme', 'maquettes', NULL, NULL, NULL, 1, 'italeri.jfif'),
	(13, 'REVELL', NULL, '2019-12-08 17:10:55', NULL, NULL, 0, NULL, NULL, 'modelisme', 'maquettes', NULL, NULL, NULL, 1, 'revell.png'),
	(14, 'GUNZE', 'Hobby Color', '2019-12-08 17:58:45', '2020-06-06 04:00:25', NULL, 0, NULL, NULL, 'peinture', NULL, NULL, NULL, NULL, 1, 'gggunze.png'),
	(15, 'Gameworkshop', 'Warrhammer', '2019-12-08 18:28:11', '2022-03-13 14:32:54', NULL, 0, NULL, NULL, 'modelisme', 'maquettes', 'figurines', 'fourniture', NULL, 1, NULL),
	(16, 'SCALE75', 'marque de figurines', '0000-00-00 00:00:00', NULL, NULL, 0, NULL, NULL, 'modelisme', 'figurines', NULL, NULL, NULL, 1, NULL),
	(17, 'ARES mythologic', 'marque de figurines', '0000-00-00 00:00:00', NULL, NULL, 0, NULL, NULL, 'modelisme', 'figurines', NULL, NULL, NULL, NULL, NULL);
/*!40000 ALTER TABLE `marque` ENABLE KEYS */;

-- Listage de la structure de la table hobby. migration_versions
CREATE TABLE IF NOT EXISTS `migration_versions` (
  `version` varchar(14) COLLATE utf8mb4_unicode_ci NOT NULL,
  `executed_at` datetime NOT NULL COMMENT '(DC2Type:datetime_immutable)',
  PRIMARY KEY (`version`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPACT;

-- Listage des données de la table hobby.migration_versions : ~12 rows (environ)
DELETE FROM `migration_versions`;
/*!40000 ALTER TABLE `migration_versions` DISABLE KEYS */;
INSERT INTO `migration_versions` (`version`, `executed_at`) VALUES
	('20191201103048', '2019-12-01 10:31:00'),
	('20191201103358', '2019-12-01 10:34:03'),
	('20191201103949', '2019-12-01 10:39:54'),
	('20191201104324', '2019-12-01 10:43:29'),
	('20191201104642', '2019-12-01 10:46:46'),
	('20191201185959', '2019-12-01 19:00:08'),
	('20191201201152', '2019-12-01 20:11:57'),
	('20191207110902', '2019-12-07 11:09:18'),
	('20191207232240', '2019-12-07 23:22:44'),
	('20191208061319', '2019-12-08 06:13:24'),
	('20191211182950', '2019-12-11 18:30:01'),
	('20200521193217', '2020-05-21 19:32:29'),
	('20210313152052', '2021-03-13 15:21:19');
/*!40000 ALTER TABLE `migration_versions` ENABLE KEYS */;

-- Listage de la structure de la table hobby. region
CREATE TABLE IF NOT EXISTS `region` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nom` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPACT;

-- Listage des données de la table hobby.region : ~3 rows (environ)
DELETE FROM `region`;
/*!40000 ALTER TABLE `region` DISABLE KEYS */;
INSERT INTO `region` (`id`, `nom`) VALUES
	(1, 'region 1'),
	(2, 'region 2'),
	(3, 'region 3');
/*!40000 ALTER TABLE `region` ENABLE KEYS */;

-- Listage de la structure de la table hobby. tag
CREATE TABLE IF NOT EXISTS `tag` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nom` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tag1` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tag2` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tag3` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tag4` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tag5` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPACT;

-- Listage des données de la table hobby.tag : ~0 rows (environ)
DELETE FROM `tag`;
/*!40000 ALTER TABLE `tag` DISABLE KEYS */;
/*!40000 ALTER TABLE `tag` ENABLE KEYS */;

-- Listage de la structure de la table hobby. ville
CREATE TABLE IF NOT EXISTS `ville` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `departement_id` int(11) NOT NULL,
  `nom` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  KEY `IDX_43C3D9C3CCF9E01E` (`departement_id`) USING BTREE,
  CONSTRAINT `FK_43C3D9C3CCF9E01E` FOREIGN KEY (`departement_id`) REFERENCES `departement` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPACT;

-- Listage des données de la table hobby.ville : ~6 rows (environ)
DELETE FROM `ville`;
/*!40000 ALTER TABLE `ville` DISABLE KEYS */;
INSERT INTO `ville` (`id`, `departement_id`, `nom`) VALUES
	(1, 1, 'ville11'),
	(2, 2, 'ville2'),
	(3, 3, 'ville3'),
	(4, 2, 'ville4'),
	(5, 3, 'ville5'),
	(6, 3, 'ville6');
/*!40000 ALTER TABLE `ville` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
