<?php

namespace App\Form;

use App\Common\dto\TagsDto;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TagDtoType extends  AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('tag1', TextType::class, [
                'label'         => false,   // 'tag1',
                'required'      => false,
            ])
            ->add('tag2', TextType::class, [
                'label'         =>  false,   // 'tag2',
                'required'      => false,
            ])
            ->add('tag3', TextType::class, [
                'label'         =>  false,   // 'tag3',
                'required'      => false,
            ])
            ->add('tag4', TextType::class, [
                'label'         =>  false,   // 'tag4',
                'required'      => false,
            ])
            ->add('tag5', TextType::class, [
                'label'         =>  false,   // 'tag5',
                'required'      => false,
            ])
            ->add('tag6', TextType::class, [
                'label'         =>  false,   // 'tag6',
                'required'      => false,
            ])
            ->add('total', TextType::class, [
                'label'         =>  false,   // 'tag6',
                'required'      => false,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => TagsDto::class,
            'method' => 'GET',
            'csrf_protection' => false,
        ]);
    }

    public function getBlockPrefix() {
        return "";
        //return parent::getBlockPrefix(); // TODO: Change the autogenerated stub
    }
}